mysite/kdt/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'kdt'
urlpatterns = [
    path('', views.index, name='index'),
    path('uploadfile/', views.upload_file, name='uploadfile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from kdt import views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='main'),
    # path('upload', views.upload),
    path('kdt/',include('kdt.urls')),
]

mysite/kdt/models.py
from django.db import models

class Audio(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.CharField(max_length=500)

    class Meta:
        managed = False
        db_table = 'audio'

mysite/kdt/wav2lip/face_detection/models.py
import torch
import torch.nn as nn
import torch.nn.functional as F
import math


def conv3x3(in_planes, out_planes, strd=1, padding=1, bias=False):
    "3x3 convolution with padding"
    return nn.Conv2d(in_planes, out_planes, kernel_size=3,
                     stride=strd, padding=padding, bias=bias)


class ConvBlock(nn.Module):
    def __init__(self, in_planes, out_planes):
        super(ConvBlock, self).__init__()
        self.bn1 = nn.BatchNorm2d(in_planes)
        self.conv1 = conv3x3(in_planes, int(out_planes / 2))
        self.bn2 = nn.BatchNorm2d(int(out_planes / 2))
        self.conv2 = conv3x3(int(out_planes / 2), int(out_planes / 4))
        self.bn3 = nn.BatchNorm2d(int(out_planes / 4))
        self.conv3 = conv3x3(int(out_planes / 4), int(out_planes / 4))

        if in_planes != out_planes:
            self.downsample = nn.Sequential(
                nn.BatchNorm2d(in_planes),
                nn.ReLU(True),
                nn.Conv2d(in_planes, out_planes,
                          kernel_size=1, stride=1, bias=False),
            )
        else:
            self.downsample = None

    def forward(self, x):
        residual = x

        out1 = self.bn1(x)
        out1 = F.relu(out1, True)
        out1 = self.conv1(out1)

        out2 = self.bn2(out1)
        out2 = F.relu(out2, True)
        out2 = self.conv2(out2)

        out3 = self.bn3(out2)
        out3 = F.relu(out3, True)
        out3 = self.conv3(out3)

        out3 = torch.cat((out1, out2, out3), 1)

        if self.downsample is not None:
            residual = self.downsample(residual)

        out3 += residual

        return out3


class Bottleneck(nn.Module):

    expansion = 4

    def __init__(self, inplanes, planes, stride=1, downsample=None):
        super(Bottleneck, self).__init__()
        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride,
                               padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, planes * 4, kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(planes * 4)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)

        if self.downsample is not None:
            residual = self.downsample(x)

        out += residual
        out = self.relu(out)

        return out


class HourGlass(nn.Module):
    def __init__(self, num_modules, depth, num_features):
        super(HourGlass, self).__init__()
        self.num_modules = num_modules
        self.depth = depth
        self.features = num_features

        self._generate_network(self.depth)

    def _generate_network(self, level):
        self.add_module('b1_' + str(level), ConvBlock(self.features, self.features))

        self.add_module('b2_' + str(level), ConvBlock(self.features, self.features))

        if level > 1:
            self._generate_network(level - 1)
        else:
            self.add_module('b2_plus_' + str(level), ConvBlock(self.features, self.features))

        self.add_module('b3_' + str(level), ConvBlock(self.features, self.features))

    def _forward(self, level, inp):
        # Upper branch
        up1 = inp
        up1 = self._modules['b1_' + str(level)](up1)

        # Lower branch
        low1 = F.avg_pool2d(inp, 2, stride=2)
        low1 = self._modules['b2_' + str(level)](low1)

        if level > 1:
            low2 = self._forward(level - 1, low1)
        else:
            low2 = low1
            low2 = self._modules['b2_plus_' + str(level)](low2)

        low3 = low2
        low3 = self._modules['b3_' + str(level)](low3)

        up2 = F.interpolate(low3, scale_factor=2, mode='nearest')

        return up1 + up2

    def forward(self, x):
        return self._forward(self.depth, x)


class FAN(nn.Module):

    def __init__(self, num_modules=1):
        super(FAN, self).__init__()
        self.num_modules = num_modules

        # Base part
        self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3)
        self.bn1 = nn.BatchNorm2d(64)
        self.conv2 = ConvBlock(64, 128)
        self.conv3 = ConvBlock(128, 128)
        self.conv4 = ConvBlock(128, 256)

        # Stacking part
        for hg_module in range(self.num_modules):
            self.add_module('m' + str(hg_module), HourGlass(1, 4, 256))
            self.add_module('top_m_' + str(hg_module), ConvBlock(256, 256))
            self.add_module('conv_last' + str(hg_module),
                            nn.Conv2d(256, 256, kernel_size=1, stride=1, padding=0))
            self.add_module('bn_end' + str(hg_module), nn.BatchNorm2d(256))
            self.add_module('l' + str(hg_module), nn.Conv2d(256,
                                                            68, kernel_size=1, stride=1, padding=0))

            if hg_module < self.num_modules - 1:
                self.add_module(
                    'bl' + str(hg_module), nn.Conv2d(256, 256, kernel_size=1, stride=1, padding=0))
                self.add_module('al' + str(hg_module), nn.Conv2d(68,
                                                                 256, kernel_size=1, stride=1, padding=0))

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)), True)
        x = F.avg_pool2d(self.conv2(x), 2, stride=2)
        x = self.conv3(x)
        x = self.conv4(x)

        previous = x

        outputs = []
        for i in range(self.num_modules):
            hg = self._modules['m' + str(i)](previous)

            ll = hg
            ll = self._modules['top_m_' + str(i)](ll)

            ll = F.relu(self._modules['bn_end' + str(i)]
                        (self._modules['conv_last' + str(i)](ll)), True)

            # Predict heatmaps
            tmp_out = self._modules['l' + str(i)](ll)
            outputs.append(tmp_out)

            if i < self.num_modules - 1:
                ll = self._modules['bl' + str(i)](ll)
                tmp_out_ = self._modules['al' + str(i)](tmp_out)
                previous = previous + ll + tmp_out_

        return outputs


class ResNetDepth(nn.Module):

    def __init__(self, block=Bottleneck, layers=[3, 8, 36, 3], num_classes=68):
        self.inplanes = 64
        super(ResNetDepth, self).__init__()
        self.conv1 = nn.Conv2d(3 + 68, 64, kernel_size=7, stride=2, padding=3,
                               bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2)
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2)
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2)
        self.avgpool = nn.AvgPool2d(7)
        self.fc = nn.Linear(512 * block.expansion, num_classes)

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                m.weight.data.normal_(0, math.sqrt(2. / n))
            elif isinstance(m, nn.BatchNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()

    def _make_layer(self, block, planes, blocks, stride=1):
        downsample = None
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                nn.Conv2d(self.inplanes, planes * block.expansion,
                          kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(planes * block.expansion),
            )

        layers = []
        layers.append(block(self.inplanes, planes, stride, downsample))
        self.inplanes = planes * block.expansion
        for i in range(1, blocks):
            layers.append(block(self.inplanes, planes))

        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)

        return x

mysite/kdt/wav2lip/models/conv.py
import torch
from torch import nn
from torch.nn import functional as F

class Conv2d(nn.Module):
    def __init__(self, cin, cout, kernel_size, stride, padding, residual=False, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.conv_block = nn.Sequential(
                            nn.Conv2d(cin, cout, kernel_size, stride, padding),
                            nn.BatchNorm2d(cout)
                            )
        self.act = nn.ReLU()
        self.residual = residual

    def forward(self, x):
        out = self.conv_block(x)
        if self.residual:
            out += x
        return self.act(out)

class nonorm_Conv2d(nn.Module):
    def __init__(self, cin, cout, kernel_size, stride, padding, residual=False, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.conv_block = nn.Sequential(
                            nn.Conv2d(cin, cout, kernel_size, stride, padding),
                            )
        self.act = nn.LeakyReLU(0.01, inplace=True)

    def forward(self, x):
        out = self.conv_block(x)
        return self.act(out)

class Conv2dTranspose(nn.Module):
    def __init__(self, cin, cout, kernel_size, stride, padding, output_padding=0, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.conv_block = nn.Sequential(
                            nn.ConvTranspose2d(cin, cout, kernel_size, stride, padding, output_padding),
                            nn.BatchNorm2d(cout)
                            )
        self.act = nn.ReLU()

    def forward(self, x):
        out = self.conv_block(x)
        return self.act(out)

mysite/kdt/views.py
from django.shortcuts import render
from .models import Audio
from . import cutsound
from . import create_sub
from . import text
from django.core.files.storage import FileSystemStorage
import os
from django.http import HttpResponse ,JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from .wav2lip import combine_model
from pydub import AudioSegment
# from .wav2lip.combine_model import lip_video_model as lip_video_model
# from ....S2S.Wav2Lip.combine_model import lip_video_model
# import sys
# sys.path.append('..\Wav2Lip')
# from ...Wav2Lip.combine_model import lip_video_model

current_directory = os.path.dirname(os.path.abspath(__file__))

def index(request):
    audio = Audio.objects.all()
    current_directory = os.path.dirname(os.path.abspath(__file__))
    print(audio)
    return render(request, 'index.html', {"audio":audio})

# 오디오 변환
def changeaudio(filename, selected_frequency):
    if selected_frequency:

            origin_path = os.path.join(current_directory, 'static','s2s','audio') # s2s 오디오
            change_path = os.path.join(current_directory, 'static','s2s','audio','change') # s2s 오디오
            
            if selected_frequency == '1':   # 저주파1
                cutsound.cutsd(filename, filename, 20 , 1000, origin_path, change_path)
            elif selected_frequency == '2': # 저주파2
                cutsound.cutsd(filename, filename, 20 , 2000, origin_path, change_path)
            elif selected_frequency == '3': # 원본
                cutsound.cutsd(filename, filename, 0 , 40000, origin_path, change_path)
            elif selected_frequency == '4': # 고주파1
                cutsound.cutsd(filename, filename, 100, 20000, origin_path, change_path)
            elif selected_frequency == '5': # 고주파2
                cutsound.cutsd(filename, filename, 200, 20000, origin_path, change_path)
    return 1

# 파일 업로드
@csrf_exempt
def upload_file(request):
    if request.method == 'POST':
        uploaded_file = request.FILES['file']
        ori_path = os.path.join(current_directory,'static','s2s','audio')

        # 기존에 파일이 존재하면 삭제 (덮어쓰기 기능)
        if os.path.exists(ori_path+'\\test.wav'):
            os.remove(os.path.join(current_directory, 'static','s2s','audio','test.wav'))
        if os.path.exists(ori_path+'\\change\\test.wav'):
            os.remove(os.path.join(current_directory, 'static','s2s','audio','change','test.wav'))

        fs = FileSystemStorage(ori_path) # 입모양에 사용할 음원 따로 저장
        num = request.POST.get('num')
        if num == 3 :
            fs = FileSystemStorage(ori_path+"\\change")

        # 주파수 저장
        audio_id = Audio.objects.latest('id').id + 1 if Audio.objects.exists() else 1 # id 얻기
        filename = f"test.wav" # 오디오 파일 이름
        print(filename)

        fs.save(filename, uploaded_file)
        audio = Audio(id=audio_id, path=fs.path(filename)) #모델에 저장
        audio.save()
        temp = Audio.objects.get(id=audio_id).path
        print(temp)

        # 주파수 모드
        # num = request.POST.get('num')
        print(num)

        changeaudio(filename,num)
        # else :
        #     fs = FileSystemStorage(os.path.join(current_directory, 'static','s2s','audio','change'))
        #     filename = f"test.wav"
        
        # 입모양 생성 여부
        generate_mouth = request.POST.get('generate_mouth')
        print(generate_mouth)
        if generate_mouth == 'yes': # 생성함
            # 원본
            combine_model.lip_video_model(ori_path+'\\'+str(filename),os.path.join(current_directory,'wav2lip','sample_data','base2.mp4'),os.path.join(current_directory,'static','s2s','video')+'\\result.mp4')

        # 텍스트 생성 여부
        generate_text = request.POST.get('generate_text')
        print(generate_text)
        if generate_text == 'yes': # 생성함
            create_sub.create_subtitles(ori_path+'\\test.wav', os.path.join(current_directory,'static','s2s','video')+'\\result.mp4', os.path.join(current_directory,'output')+'\\created_sub.srt', os.path.join(current_directory,'static', 'font')+'\\KCC-Ganpan.woff2', os.path.join(current_directory,'static','s2s','video')+'\\final.mp4',os.path.join(current_directory, 'static','s2s','audio','test.wav'))

        if generate_mouth == 'no' and generate_text == 'yes': # 주파수만 선택된 경우
            print("21341233")
            text.only_text(ori_path+'\\'+str(filename), os.path.join(current_directory+"\\cover.jpg"), os.path.join(current_directory,'output')+'\\created_sub.srt', os.path.join(current_directory,'static', 'font')+'\\KCC-Ganpan.woff2', os.path.join(current_directory,'static','s2s','video')+'\\final.mp4', os.path.join(current_directory, 'static','s2s','audio','change','test.wav'))


# add_subtitles(video_path, srt_path, output_path)
        context = {
            'num': num,
            'generate_mouth': generate_mouth,
            'generate_text': generate_text,
            'filename' : filename,
            'path' : temp,
        }
        message = '파일이 성공적으로 업로드되었습니다.'
        return render(request, 'model_result.html', context)
        # 사용한 파일 삭제
    return render(request, 'upload_file.html')

mysite/kdt/templates/audio.html
오디오 변환중..

mysite/kdt/templates/base.html
{% load static %}

<head>
    <title>S2S</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- 부트스트랩 아이콘 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body class="app">
    <div class="d-flex justify-content-between mx-4">
        <a href={% url "main" %} class="nav-text"><i class="bi bi-house"></i> HOME</a>
        <a href={% url "kdt:uploadfile" %} class="nav-text align-self-end"><i class="bi bi-play"></i> SERVICE</a>

    </div>
    
    <section>
        <div class="container mt-4">
    
            <!-- 제목 Start -->
            <div class="mt-3">
                <div class="main-text-01">S2S</div>
                <div class="main-text-02">Sound to Show</div>
            </div>
            <!-- 제목 End -->

        </div>
    </section>
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- 기본 템플릿 안에 삽입될 Javascript Start -->
    {% block script %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 Javascript End -->
</body>

mysite/kdt/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="app main-page">
    <div class="container p-5">

        <div class="text-center">
            <a href="{% url 'kdt:uploadfile' %}"
            class="btn btn-lg btn-secondary">
                Get Started!
            </a>
        </div>

        <!-- 설명 Start -->
        <div class="main-detail my-5 p-4">
    
            <div class="mb-5">
                <div class="content-bold">
                    본 프로젝트는 경증 청각장애인에게 <span class="text-danger">변환된 음성</span>과 <span class="text-danger">입모양 시각화 영상 및 텍스트</span>를 제공하여,<br>
                    학업 성취도 및 사회 참여 기회를 증진시키기 위한 서비스입니다.
                </div>
            </div>

            <h5 class="">
                음원을 업로드하면, 변환된 음원 또는 영상을 제공해드립니다.
            </h5>
            <h5 class="my-3">
                먼저, 본인의 가청주파수를 알아보기 위해 다음 버튼을 클릭해주세요!
            </h5>

            <a href="https://hi098123.tistory.com/295" target="_blank" class="btn btn-outline-info align-self-start my-2">
                가청 주파수 확인
            </a>
            
        </div>
        <br>
        <!-- 설명 End -->

        <div class="d-flex justify-content-center my-5">

            <div class="main-img-01 mx-3 p-5">

                <h1 class="content-bold d-flex justify-content-center mt-4">
                    Step 1
                </h1>
                <h4 class="d-flex justify-content-center mt-4">
                    주파수 모드 설정
                </h4>

                <div class="d-flex justify-content-center my-5">
                    <img class="img-fluid" src="{% static 'img/tmp1.png' %}" alt="frequency">
                </div>

                <p class="text-center mt-4">
                    네가지의 변환 음원과 원본 음원을<br>
                    선택할 수 있습니다.
                </p>

            </div>
    
            <div class="main-img-01 mx-3 p-5">
                
                <h1 class="content-bold d-flex justify-content-center mt-4">
                    Step 2
                </h1>
                <h4 class="d-flex justify-content-center mt-4">
                    입모양 시각화 여부 설정
                </h4>

                <div class="d-flex justify-content-center my-5">
                    <img class="img-fluid" src="{% static 'img/tmp2.png' %}" alt="lip">
                </div>

                <p class="text-center mt-4">
                    음원의 입모양을 시각화한 얼굴 영상을<br>
                    제공합니다.<br>
                    시각화 여부를 선택할 수 있습니다.
                </p>

            </div>
    
            <div class="main-img-01 mx-3 p-5">

                <h1 class="content-bold d-flex justify-content-center mt-4">
                    Step 3
                </h1>
                <h4 class="d-flex justify-content-center mt-4">
                    텍스트 시각화 여부 설정
                </h4>

                <div class="d-flex justify-content-center my-5">
                    <img class="img-fluid" src="{% static 'img/tmp4.png' %}" alt="text">
                </div>

                <p class="text-center mt-4">
                    음원의 텍스트를 추출하여 제공합니다.<br>
                    시각화 여부를 선택할 수 있습니다.
                </p>

            </div>
    
        </div>

    </div>
</section>
{% endblock %}

mysite/kdt/templates/lipvideo.html
비디오 생성 완료

mysite/kdt/templates/model_result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="">
        <div class="container py-3">
            <div class="main-detail row my-5 d-flex justify-content-center">
                <div class="col-lg-4 mx-3 p-5 align-self-center">

                    <legend class="content-bold mb-3" style="font-size:35px;">결과 영상/음원 출력</legend>
                    <p class="text-center mb-5">
                        아래에서 결과 영상/음원을 확인해보세요!
                    </p>

                    <h5 class="content-bold pt-4">
                        선택한 설정
                    </h5>
                    <div class="mt-3 mb-5">
                        <p>
                            {% if num == '1' %} 고주파 1 (1,000~20,000Hz) 음원
                            {% elif num == '2' %} 고주파 2 (2,000~20,000Hz) 음원
                            {% elif num == '3' %} 원본 음원
                            {% elif num == '4' %} 저주파 1 (20~1,000Hz) 음원
                            {% elif num == '5' %} 저주파 2 (20~2,000Hz) 음원
                            {% endif %}
                        </p>
                        <p>입모양 생성{% if generate_mouth == "yes" %}함{% else %} 안함{% endif %}</p>
                        <p>텍스트 생성{% if generate_text == "yes" %}함{% else %} 안함{% endif %}</p>
                    </div>
                      
                </div>

                <div class="col-lg-6 mx-3 p-5">
                    {% if generate_mouth == 'yes' or generate_text == 'yes'%}
                        <video class="justify-content-center main-detail " width="400" height="auto" controls>
                            <source src="{% static "s2s/video/final.mp4" %}" type="video/mp4">
                            {% comment %} <source src="movie.ogg" type="video/ogg"> {% endcomment %}
                            브라우저에서 지원되는 포맷이 아닙니다.
                        </video>
                    {% endif %}
                    {% if generate_mouth == 'no' and generate_text == 'no' %}
                        <audio class="justify-content-center mt-5" style="width:400" controls>
                            <source src="{% static "s2s/audio/change/test.wav" %}" type="audio/mpeg">
                            브라우저에서 지원되는 포맷이 아닙니다.
                        </audio>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mysite/kdt/templates/upload.html
<h1>Save File</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file">
    <button type="submit">업로드</button>
</form>
  
    {% if message %}
    <p>{{ message }}</p>
    {% endif %}